<?xml version="1.0" encoding="UTF-8" ?><?xml-stylesheet type="text/xsl" href="testharness.xsl"?><testharness><message><timestamp>2021-04-06 08:37:30.923389</timestamp><level>user</level><value>Argument parse SERIAL mode connecting to COM24 , flow control: rts-cts </value></message><message><timestamp>2021-04-06 08:37:30.957391</timestamp><level>error</level><value>Traceback (most recent call last):
  File "C:\Python\testharness\utility.py", line 96, in do_testharness
    t()
  File "C:\Python\putfile.py", line 20, in putfile
    req_unsolicited = conn.connect()
  File "C:\Python\testharness\connection.py", line 127, in connect
    use_xonxoff = (result.flow_ctrl == 'xon-xoff'))
  File "C:\Python\testharness\connection.py", line 73, in connect_serial
    dsrdtr = use_dsrdtr, rtscts = use_rtscts, xonxoff = use_xonxoff
  File "C:\Users\jon.bianco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\serial\serialwin32.py", line 38, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Users\jon.bianco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\serial\serialutil.py", line 282, in __init__
    self.open()
  File "C:\Users\jon.bianco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\serial\serialwin32.py", line 66, in open
    raise SerialException("could not open port %r: %r" % (self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM24': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
 </value></message></testharness>